# Generated by Django 4.1.13 on 2023-11-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст')),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d/', verbose_name='Изображение')),
            ],
        ),
    ]
