# Generated by Django 4.1.13 on 2023-11-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadedfiles',
            options={'verbose_name': 'Загруженный файл', 'verbose_name_plural': 'Загруженные файлы'},
        ),
    ]
