# Generated by Django 4.1.13 on 2023-11-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_loadedfiles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedfiles',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
    ]
