# Generated by Django 4.1.13 on 2023-11-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_loadedfiles_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedfiles',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст'),
        ),
    ]
