# Generated by Django 4.1.13 on 2023-11-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_loadedfiles_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedfiles',
            name='file',
            field=models.ImageField(upload_to='upload/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
