# Generated by Django 4.1.13 on 2023-11-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_loadeddocuments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadedDocuments',
        ),
    ]
