# Generated by Django 4.1.13 on 2023-11-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
