# Generated by Django 4.1.13 on 2023-11-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('uploadedFile', models.FileField(upload_to='upload/%Y/%m/%d/', verbose_name='Файл')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
    ]
