# Generated by Django 4.2.7 on 2024-10-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], default='2024', max_length=4, verbose_name='Год'),
        ),
    ]
