# Generated by Django 4.1.13 on 2023-11-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Порядковый №'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Actual', 'Actual'), ('Archive', 'Archive')], default='Actual', max_length=7, verbose_name='Статус'),
        ),
    ]
