# Generated by Django 4.1.13 on 2023-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_post_order_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('ACT', 'Актуально'), ('ARC', 'Архив')], default='ACT', max_length=3, verbose_name='Статус'),
        ),
    ]
