# Generated by Django 4.1.13 on 2023-11-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('file_docu', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Загруженный документ',
                'verbose_name_plural': 'Загруженные документы',
            },
        ),
    ]
