# Generated by Django 4.1.13 on 2023-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadeddocuments',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Иконка'),
        ),
    ]
