# Generated by Django 4.1.13 on 2023-11-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovokosulinoArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2024', max_length=4, verbose_name='Год')),
                ('text', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('uploadedImage', models.ImageField(upload_to='village/%Y/%m/%d/', verbose_name='Файл')),
                ('dateOfUpload', models.DateField(auto_now=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'АРХИВ "Новокосулино-2"',
                'verbose_name_plural': 'АРХИВ "Новокосулино-2"',
            },
        ),
    ]
