# Generated by Django 4.2.7 on 2024-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_novokosulinoarchive_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NY2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedImage', models.ImageField(upload_to='NY2024/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Новый Год 2024',
                'verbose_name_plural': 'Новый Год 2024',
            },
        ),
    ]
