# Generated by Django 4.2.7 on 2024-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_ny2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ny2024',
            name='uploadedImage',
            field=models.ImageField(upload_to='archive/NY2024/', verbose_name='Файл'),
        ),
    ]
