# Generated by Django 4.2.7 on 2024-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_alter_ny2024_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maslenitsa2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedImage', models.ImageField(upload_to='archive/Maslenitsa2024/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Масленица 2024',
                'verbose_name_plural': 'Масленица 2024',
            },
        ),
    ]
