# Generated by Django 4.2.7 on 2024-12-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_maslenitsa2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='NY2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedImage', models.ImageField(upload_to='archive/NY2025/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Новый Год 2025',
                'verbose_name_plural': 'Новый Год 2025',
            },
        ),
    ]
