# Generated by Django 4.2.7 on 2025-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0007_ny2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maslenitsa2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedImage', models.ImageField(upload_to='archive/Maslenitsa2025/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Масленица 2025',
                'verbose_name_plural': 'Масленица 2025',
            },
        ),
    ]
