# Generated by Django 4.2.7 on 2023-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadeddocuments',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата документа'),
        ),
    ]
