# Generated by Django 4.2.7 on 2024-05-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_docu', '0003_category_loadeddocuments_content_loadeddocuments_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadeddocuments',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='docus', to='app_docu.category', verbose_name='Категории'),
            preserve_default=False,
        ),
    ]
