# Generated by Django 4.2.7 on 2024-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docu', '0004_alter_loadeddocuments_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadeddocuments',
            name='file_docu',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
